window.questions =[
{questions:'Cuantos personas van asistir?',
 answer1:25,
 answer2:50,
 answer3:75,
 answer4:[100,'+']},
{questions:'Cuanto meseros necesitaras?',
answer1:5,
answer2:10,
answer3:15,
answer4:[20,'+']},
{questions:'Que tipo de bebidas van a querer? *(selecciona todos los que applican)',
answer1:'refresco',
answer2:'aguas',
answer3:'cafe',
answer4:'cerveza'},
{questions:'Que tipo de comida les gustaria tener? *(selecciona todos los que applican)',
answer1:'vegetariana',
answer2:'cortes de carne',
answer3:'tacos',
answer4:'quesadillas'},
{questions:'Que tipo de postre quieren? *(selecciona todos los que applican)',
answer1:'pastel',
answer2:'churros',
answer3:'cheesecake',
answer4:'helado'}
]
